services:
  policy-translator:
    build: .
    container_name: policy-translator
    ports:
      - "5005:5005"
    restart: always
    environment:
      - ORCHESTRATOR_IP=10.208.11.74
      - PROMETHEUS_PORT=32047
    networks:
    - kind

networks:
  kind:
    external: true
