services:
  policy-translator:
    build: .
    container_name: policy-translator
    ports:
      - "5005:5005"
    restart: always
    environment:
      - ORCHESTRATOR_URL=http://10.208.99.74:8002/meservice
    networks:
    - kind

networks:
  kind:
    external: true