services:
  policy-translator:
    build: .
    container_name: policy-translator
    ports:
      - "5005:5005"
    restart: always
    environment:
      - ORCHESTRATOR_IP=10.208.11.74
      - PROMETHEUS_ADDR=172.18.0.2:32047
      - IBI_ADDR=10.208.11.73:8003
    networks:
    - kind

networks:
  kind:
    external: true
