# .github/workflows/pt.yml

name: PT CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login "${{ secrets.GHCR_URL }}" -u "${{ github.actor }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.GHCR_IMAGE }} .
          docker push ${{ secrets.GHCR_IMAGE }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login "${{ secrets.GHCR_URL }}" -u "${{ github.actor }}" --password-stdin

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      #- name: Create shared-network
      #  run: docker network create shared-network

      - name: Run docker-compose
        run: docker-compose up -d 
        
      #- name: Wait for orchestrator service to be ready
      #  run: |
      #    while ! curl -s http://localhost:8002 > /dev/null; do
      #      echo "Waiting for orchestrator service..."
      #      sleep 5
      #    done

      - name: Wait for policy_translator service to be ready
        run: |
          while ! curl -s http://localhost:5005 > /dev/null; do
            echo "Waiting for policy_translator service..."
            sleep 5
          done

      - name: Run get request.json translation
        run: |
          echo "XML translation:"
          curl -s -X POST -H "Cache-Control: no-cache" -H "Content-Type: application/json" -d @request.json http://localhost:5005/api -o response.xml
          cat response.xml

      - name: Test /send_policy endpoint
        run: |
          echo "JSON translation"
          curl -s -X POST -H "Cache-Control: no-cache" -H "Content-Type: application/json" -d @request.json http://localhost:5005/send_policy -o response.json
          cat response.json

      - name: Wait 10 seconds
        run: sleep 10

      #- name: Check Docker container logs for orchestrator
      #  run: docker logs orchestrator

      - name: Check Docker container logs for policy_translator
        run: docker logs policy_translator

      - name: Stop Docker container
        run: docker-compose down
